DROP DATABASE IF EXISTS tomalgo;
CREATE DATABASE tomalgo;
USE tomalgo;	

CREATE TABLE USER (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username varchar(30) NOT NULL UNIQUE KEY,
  password binary(20) NOT NULL,
  mail varchar (40) NOT NULL,
  street TEXT,
  birth date,
  enterprise boolean NOT NULL,
  enable boolean NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE EVENT (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  enterprise INTEGER NOT NULL,
  text varchar (160) NOT NULL,
  inidate DATETIME NOT NULL,
  enddate DATETIME NOT NULL,
  promo BOOLEAN NOT NULL,
  FOREIGN KEY (enterprise) REFERENCES USER (id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TAG (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name varchar (30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE RL_TAG (
  user INTEGER NOT NULL,
  tag INTEGER NOT NULL,
  PRIMARY KEY (user, tag),
  FOREIGN KEY (user) REFERENCES USER(id),
  FOREIGN KEY (tag) REFERENCES TAG(id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE RL_EVENT (
  user INTEGER NOT NULL,
  event INTEGER NOT NULL,
  PRIMARY KEY (user, event),
  FOREIGN KEY (user) REFERENCES USER(id),
  FOREIGN KEY (event) REFERENCES EVENT(id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;